---
title: "DOC Workup"
author: "Wesley Sparagon"
date: "11/4/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Load libraries and read in metadata and raw DOC data.

```{r}
DOC_raw <- read.csv(file.path(dirRAW, "DOC", "DOC_with_SampleName.csv"))
metadata <- read.csv(file.path(dirRAW, "Metadata.csv"))
```

Remove outlier samples, as identified from the DOC sample notes in the "MO19_ABC_NPOC.2020.01.22_summary_with_notes.xlsx" raw data document.

```{r}
dat <- DOC_raw[c(-1,-11,-14,-17,-19,-23,-34),]
```

Merge with metadata.

```{r}
#subset for only DOC metadata
metadata.doc <- metadata[metadata$Sample_Type=="DOC",]

#merge with DOC dat
DOC_dat <- merge(dat, metadata.doc, by.x="Sample.Name", by.y="Sample.Name", all.x=T, all.y=F)
```

Calculate the background water control corrected DOC for the t0 samples.

```{r}
#calcualte background water control DOC values
ambient_background = mean(DOC_dat$uMC[DOC_dat$Treatment=="Ambient Water Control" & DOC_dat$Timepoint==0]) #calcualte ambient background
heated_background = mean(DOC_dat$uMC[DOC_dat$Treatment=="Heated Water Control" & DOC_dat$Timepoint==0]) #calcualte ambient background

#Add a new column corresponding to DOC background values for every sample.
DOC_dat$Background_DOC = DOC_dat$uMC #first copy DOC values
DOC_dat$Background_DOC[DOC_dat$Stress_status == "Thermal Stress"] = heated_background #in the background DOC column, for any sample which was thermally stressed add corresponding heated background value.
DOC_dat$Background_DOC[DOC_dat$Stress_status == "Ambient"] = ambient_background #in the background DOC column, for any sample which was ambient add corresponding ambient background value.

#Calculate control corrected DOC by subtracting the background value from the DOC value.
DOC_dat$Control_Corrected_DOC = DOC_dat$uMC - DOC_dat$Background_DOC
```


Export.

```{r}
write.csv(DOC_dat, file.path(dirOutput, "DOC_dat.csv"), )
```

